// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pulse.Api.ApiService.Data;

#nullable disable

namespace Pulse.Api.ApiService.Data.Migrations
{
    [DbContext(typeof(PulseDbContext))]
    [Migration("20260630155858_PulseNote")]
    partial class PulseNote
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Pulse.Api.ApiService.Domain.Connection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ConnectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("connected_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("InviteCode")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("invite_code");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("timezone");

                    b.Property<Guid>("UserAId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_a_id");

                    b.Property<Guid?>("UserBId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_b_id");

                    b.HasKey("Id")
                        .HasName("pk_connections");

                    b.HasIndex("InviteCode")
                        .IsUnique()
                        .HasDatabaseName("ix_connections_invite_code")
                        .HasFilter("invite_code IS NOT NULL");

                    b.HasIndex("UserAId")
                        .HasDatabaseName("ix_connections_user_a_id");

                    b.HasIndex("UserBId")
                        .HasDatabaseName("ix_connections_user_b_id");

                    b.ToTable("connections", (string)null);
                });

            modelBuilder.Entity("Pulse.Api.ApiService.Domain.ConnectionPack", b =>
                {
                    b.Property<Guid>("ConnectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("connection_id");

                    b.Property<Guid>("PackId")
                        .HasColumnType("uuid")
                        .HasColumnName("pack_id");

                    b.Property<DateTimeOffset>("AddedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("added_at");

                    b.HasKey("ConnectionId", "PackId")
                        .HasName("pk_connection_packs");

                    b.HasIndex("PackId")
                        .HasDatabaseName("ix_connection_packs_pack_id");

                    b.ToTable("connection_packs", (string)null);
                });

            modelBuilder.Entity("Pulse.Api.ApiService.Domain.Moment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ConnectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("connection_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("boolean")
                        .HasColumnName("is_favorite");

                    b.Property<int>("SequenceNumber")
                        .HasColumnType("integer")
                        .HasColumnName("sequence_number");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("template_id");

                    b.HasKey("Id")
                        .HasName("pk_moments");

                    b.HasIndex("TemplateId")
                        .HasDatabaseName("ix_moments_template_id");

                    b.HasIndex("ConnectionId", "Date")
                        .IsUnique()
                        .HasDatabaseName("ix_moments_connection_id_date");

                    b.HasIndex("ConnectionId", "SequenceNumber")
                        .HasDatabaseName("ix_moments_connection_id_sequence_number");

                    b.ToTable("moments", (string)null);
                });

            modelBuilder.Entity("Pulse.Api.ApiService.Domain.MomentResponse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("ChoiceIndex")
                        .HasColumnType("integer")
                        .HasColumnName("choice_index");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Emoji")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("emoji");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("kind");

                    b.Property<Guid>("MomentId")
                        .HasColumnType("uuid")
                        .HasColumnName("moment_id");

                    b.Property<string>("PhotoPath")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("photo_path");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(800)
                        .HasColumnType("character varying(800)")
                        .HasColumnName("photo_url");

                    b.Property<string>("StrokeData")
                        .HasColumnType("jsonb")
                        .HasColumnName("stroke_data");

                    b.Property<string>("Text")
                        .HasMaxLength(280)
                        .HasColumnType("character varying(280)")
                        .HasColumnName("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("VoicePath")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("voice_path");

                    b.Property<string>("VoiceUrl")
                        .HasMaxLength(800)
                        .HasColumnType("character varying(800)")
                        .HasColumnName("voice_url");

                    b.HasKey("Id")
                        .HasName("pk_moment_responses");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_moment_responses_user_id");

                    b.HasIndex("MomentId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_moment_responses_moment_id_user_id");

                    b.ToTable("moment_responses", (string)null);
                });

            modelBuilder.Entity("Pulse.Api.ApiService.Domain.MomentTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("category");

                    b.Property<string>("Options")
                        .HasColumnType("jsonb")
                        .HasColumnName("options");

                    b.Property<Guid>("PackId")
                        .HasColumnType("uuid")
                        .HasColumnName("pack_id");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("prompt");

                    b.Property<string>("ResponseKind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("response_kind");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_moment_templates");

                    b.HasIndex("PackId")
                        .HasDatabaseName("ix_moment_templates_pack_id");

                    b.ToTable("moment_templates", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("c0ac7185-e523-5ff6-716b-0d0f79ae6aec"),
                            Category = "Capture",
                            PackId = new Guid("a07a6b6e-62f5-dd5c-5c66-1a8d085aa450"),
                            Prompt = "Photograph something that made you smile today.",
                            ResponseKind = "Photo",
                            Title = "Smile"
                        },
                        new
                        {
                            Id = new Guid("1c6a4473-523f-3e6b-3967-2f5b1df1f6b9"),
                            Category = "Capture",
                            PackId = new Guid("a07a6b6e-62f5-dd5c-5c66-1a8d085aa450"),
                            Prompt = "Capture something that's your favourite colour.",
                            ResponseKind = "Photo",
                            Title = "Favourite colour"
                        },
                        new
                        {
                            Id = new Guid("0a36c1e8-b0b3-2566-782d-b25812db995d"),
                            Category = "Capture",
                            PackId = new Guid("a07a6b6e-62f5-dd5c-5c66-1a8d085aa450"),
                            Prompt = "Find beauty in something most people would walk past.",
                            ResponseKind = "Photo",
                            Title = "Tiny detail"
                        },
                        new
                        {
                            Id = new Guid("d6e73489-f577-cea7-73af-d4b3b3fbd39d"),
                            Category = "Capture",
                            PackId = new Guid("a07a6b6e-62f5-dd5c-5c66-1a8d085aa450"),
                            Prompt = "Capture today's weather.",
                            ResponseKind = "Photo",
                            Title = "Seasons"
                        },
                        new
                        {
                            Id = new Guid("489c1a9a-d137-452b-0194-e37e93d5b5b9"),
                            Category = "Micro",
                            PackId = new Guid("a07a6b6e-62f5-dd5c-5c66-1a8d085aa450"),
                            Prompt = "One photo. No caption.",
                            ResponseKind = "Photo",
                            Title = "One photo"
                        },
                        new
                        {
                            Id = new Guid("40a64f3a-739d-24b8-5ac8-2f9c78631c56"),
                            Category = "Draw",
                            PackId = new Guid("a07a6b6e-62f5-dd5c-5c66-1a8d085aa450"),
                            Prompt = "Draw your perfect Sunday.",
                            ResponseKind = "Drawing",
                            Title = "Perfect Sunday"
                        },
                        new
                        {
                            Id = new Guid("eefbe0f2-60d5-c07d-fb40-cb3aa6347126"),
                            Category = "Draw",
                            PackId = new Guid("a07a6b6e-62f5-dd5c-5c66-1a8d085aa450"),
                            Prompt = "Sketch your dream home.",
                            ResponseKind = "Drawing",
                            Title = "Dream house"
                        },
                        new
                        {
                            Id = new Guid("e4b85faa-b4c1-f8e4-24de-822be82fd25a"),
                            Category = "Draw",
                            PackId = new Guid("a07a6b6e-62f5-dd5c-5c66-1a8d085aa450"),
                            Prompt = "Draw yourself from memory.",
                            ResponseKind = "Drawing",
                            Title = "Self portrait"
                        },
                        new
                        {
                            Id = new Guid("54642194-9e81-d090-9903-c352705f1900"),
                            Category = "Draw",
                            PackId = new Guid("a07a6b6e-62f5-dd5c-5c66-1a8d085aa450"),
                            Prompt = "Both draw an animal. Reveal together.",
                            ResponseKind = "Drawing",
                            Title = "Guess"
                        },
                        new
                        {
                            Id = new Guid("43fb2e70-5a08-aaa0-9f57-c46adb043bd4"),
                            Category = "Micro",
                            PackId = new Guid("a07a6b6e-62f5-dd5c-5c66-1a8d085aa450"),
                            Prompt = "Draw one thing.",
                            ResponseKind = "Drawing",
                            Title = "One doodle"
                        },
                        new
                        {
                            Id = new Guid("edc5ab2f-7a97-aee9-ca95-dfbd48339d8f"),
                            Category = "LoveLetter",
                            PackId = new Guid("a07a6b6e-62f5-dd5c-5c66-1a8d085aa450"),
                            Prompt = "One thing I appreciated today.",
                            ResponseKind = "Text",
                            Title = "Appreciation"
                        },
                        new
                        {
                            Id = new Guid("65976f8d-b3b0-8673-8e76-f49cac7f6c2f"),
                            Category = "LoveLetter",
                            PackId = new Guid("a07a6b6e-62f5-dd5c-5c66-1a8d085aa450"),
                            Prompt = "Something you've never thanked them for.",
                            ResponseKind = "Text",
                            Title = "Thank you"
                        },
                        new
                        {
                            Id = new Guid("6b396ea2-b3df-1ea3-0cf0-b97dd8b2b13b"),
                            Category = "LoveLetter",
                            PackId = new Guid("a07a6b6e-62f5-dd5c-5c66-1a8d085aa450"),
                            Prompt = "My favourite thing about you this week.",
                            ResponseKind = "Text",
                            Title = "Favourite"
                        },
                        new
                        {
                            Id = new Guid("77a8adec-d0a6-c05c-7a3d-71b5a3fc8f2b"),
                            Category = "LoveLetter",
                            PackId = new Guid("a07a6b6e-62f5-dd5c-5c66-1a8d085aa450"),
                            Prompt = "One thing I'm looking forward to.",
                            ResponseKind = "Text",
                            Title = "Future"
                        },
                        new
                        {
                            Id = new Guid("4f32102f-7280-d6a9-52ff-a55adf11bd07"),
                            Category = "Fun",
                            Options = "[\"\\uD83C\\uDF55 Pizza\",\"\\uD83C\\uDF54 Burger\"]",
                            PackId = new Guid("a07a6b6e-62f5-dd5c-5c66-1a8d085aa450"),
                            Prompt = "Pizza or Burger? Pick your favourite.",
                            ResponseKind = "Choice",
                            Title = "This or That"
                        },
                        new
                        {
                            Id = new Guid("45c3b95d-837b-7cbc-40ca-d2f50e3018c7"),
                            Category = "Fun",
                            Options = "[\"\\u26F0\\uFE0F Mountains\",\"\\uD83C\\uDFD6\\uFE0F Beach\",\"\\uD83C\\uDFD9\\uFE0F City\"]",
                            PackId = new Guid("a07a6b6e-62f5-dd5c-5c66-1a8d085aa450"),
                            Prompt = "Pick your favourite!",
                            ResponseKind = "Choice",
                            Title = "Would You Rather?"
                        },
                        new
                        {
                            Id = new Guid("bdbe1627-849f-4004-e5f1-5d43e316dfb2"),
                            Category = "Fun",
                            Options = "[\"\\uD83D\\uDC31 Cats\",\"\\uD83D\\uDC36 Dogs\"]",
                            PackId = new Guid("a07a6b6e-62f5-dd5c-5c66-1a8d085aa450"),
                            Prompt = "Cats or dogs?",
                            ResponseKind = "Choice",
                            Title = "Secret vote"
                        },
                        new
                        {
                            Id = new Guid("f2713a6d-04df-7129-b6f2-ae21bd251539"),
                            Category = "Fun",
                            PackId = new Guid("a07a6b6e-62f5-dd5c-5c66-1a8d085aa450"),
                            Prompt = "Describe your day using only emojis.",
                            ResponseKind = "Text",
                            Title = "Emoji story"
                        },
                        new
                        {
                            Id = new Guid("e7ed1cbc-821a-2e93-97c0-d9eaffff245a"),
                            Category = "Voice",
                            PackId = new Guid("a07a6b6e-62f5-dd5c-5c66-1a8d085aa450"),
                            Prompt = "Leave a 20-second morning message.",
                            ResponseKind = "Voice",
                            Title = "Good morning"
                        },
                        new
                        {
                            Id = new Guid("f0512d14-d8ba-7e37-0bca-89064a6f9c0a"),
                            Category = "Voice",
                            PackId = new Guid("a07a6b6e-62f5-dd5c-5c66-1a8d085aa450"),
                            Prompt = "Share a story you've never told.",
                            ResponseKind = "Voice",
                            Title = "Tell me something"
                        },
                        new
                        {
                            Id = new Guid("a46b7677-e097-cdd9-87ca-85771a488ba8"),
                            Category = "Voice",
                            PackId = new Guid("a07a6b6e-62f5-dd5c-5c66-1a8d085aa450"),
                            Prompt = "Record your best laugh.",
                            ResponseKind = "Voice",
                            Title = "Laugh"
                        },
                        new
                        {
                            Id = new Guid("55d333df-d4bc-2f86-8485-c66d3abe06a2"),
                            Category = "Adventure",
                            PackId = new Guid("a07a6b6e-62f5-dd5c-5c66-1a8d085aa450"),
                            Prompt = "Walk somewhere you've never been.",
                            ResponseKind = "Photo",
                            Title = "Walk"
                        },
                        new
                        {
                            Id = new Guid("1cb2df20-21d4-e065-b97b-4056de6f7892"),
                            Category = "Adventure",
                            PackId = new Guid("a07a6b6e-62f5-dd5c-5c66-1a8d085aa450"),
                            Prompt = "Try a new café.",
                            ResponseKind = "Photo",
                            Title = "Coffee"
                        },
                        new
                        {
                            Id = new Guid("d3899992-5ddb-651c-8c95-326794de7502"),
                            Category = "Adventure",
                            PackId = new Guid("a07a6b6e-62f5-dd5c-5c66-1a8d085aa450"),
                            Prompt = "Watch today's sunset.",
                            ResponseKind = "Photo",
                            Title = "Sunset"
                        },
                        new
                        {
                            Id = new Guid("fcc50a36-a32c-886d-84d8-1e7911bba401"),
                            Category = "Adventure",
                            PackId = new Guid("a07a6b6e-62f5-dd5c-5c66-1a8d085aa450"),
                            Prompt = "Find something heart-shaped outside.",
                            ResponseKind = "Photo",
                            Title = "Find"
                        },
                        new
                        {
                            Id = new Guid("44e97470-c9df-9816-d2eb-daac7b00cbc0"),
                            Category = "Reflection",
                            PackId = new Guid("a07a6b6e-62f5-dd5c-5c66-1a8d085aa450"),
                            Prompt = "What was today's best moment?",
                            ResponseKind = "Text",
                            Title = "Best part"
                        },
                        new
                        {
                            Id = new Guid("269a7c76-5193-3b40-a9b5-24a98b2c2e26"),
                            Category = "Reflection",
                            PackId = new Guid("a07a6b6e-62f5-dd5c-5c66-1a8d085aa450"),
                            Prompt = "What's one thing you're proud of today?",
                            ResponseKind = "Text",
                            Title = "Win"
                        },
                        new
                        {
                            Id = new Guid("ebe43843-2a65-0da5-67aa-3aab91231ffe"),
                            Category = "Reflection",
                            PackId = new Guid("a07a6b6e-62f5-dd5c-5c66-1a8d085aa450"),
                            Prompt = "What was difficult today?",
                            ResponseKind = "Text",
                            Title = "Challenge"
                        },
                        new
                        {
                            Id = new Guid("7164603c-29cb-16a2-edaf-d3a67d715301"),
                            Category = "Reflection",
                            PackId = new Guid("a07a6b6e-62f5-dd5c-5c66-1a8d085aa450"),
                            Prompt = "What's one thing you're excited for?",
                            ResponseKind = "Text",
                            Title = "Tomorrow"
                        },
                        new
                        {
                            Id = new Guid("064285a4-baa0-b0a0-bfba-781325551437"),
                            Category = "Micro",
                            PackId = new Guid("a07a6b6e-62f5-dd5c-5c66-1a8d085aa450"),
                            Prompt = "Describe today in one word.",
                            ResponseKind = "Text",
                            Title = "One word"
                        },
                        new
                        {
                            Id = new Guid("eb79632f-20cb-3e89-8c40-5a4e65b81457"),
                            Category = "Micro",
                            PackId = new Guid("a07a6b6e-62f5-dd5c-5c66-1a8d085aa450"),
                            Prompt = "How was today?",
                            ResponseKind = "Text",
                            Title = "One emoji"
                        },
                        new
                        {
                            Id = new Guid("3d7daa2f-1ef8-f7b9-da36-9b18d18e45c8"),
                            Category = "Capture",
                            PackId = new Guid("e172da09-9a11-fa64-c9af-ea552326293b"),
                            Prompt = "Capture the light at golden hour.",
                            ResponseKind = "Photo",
                            Title = "Golden hour"
                        },
                        new
                        {
                            Id = new Guid("d1709834-2a51-7e15-c535-f73992153eb4"),
                            Category = "Capture",
                            PackId = new Guid("e172da09-9a11-fa64-c9af-ea552326293b"),
                            Prompt = "Find leading lines in your surroundings.",
                            ResponseKind = "Photo",
                            Title = "Leading lines"
                        },
                        new
                        {
                            Id = new Guid("b7124984-4a33-3a96-6b33-23a2fab1ca81"),
                            Category = "Capture",
                            PackId = new Guid("e172da09-9a11-fa64-c9af-ea552326293b"),
                            Prompt = "Photograph a reflection.",
                            ResponseKind = "Photo",
                            Title = "Reflections"
                        },
                        new
                        {
                            Id = new Guid("0dfdcbdb-9843-ac8b-a07f-7657dc1d6ce7"),
                            Category = "Capture",
                            PackId = new Guid("e172da09-9a11-fa64-c9af-ea552326293b"),
                            Prompt = "Capture an interesting shadow.",
                            ResponseKind = "Photo",
                            Title = "Shadows"
                        },
                        new
                        {
                            Id = new Guid("673a8d11-222e-2f77-5bf6-b9a8dffa31b1"),
                            Category = "Adventure",
                            PackId = new Guid("4a1394b9-499d-15e5-78c6-afe1634365c4"),
                            Prompt = "Walk a street you've never walked.",
                            ResponseKind = "Photo",
                            Title = "New street"
                        },
                        new
                        {
                            Id = new Guid("eb4a957b-1338-ba4a-c0db-d96f6e3a4417"),
                            Category = "Adventure",
                            PackId = new Guid("4a1394b9-499d-15e5-78c6-afe1634365c4"),
                            Prompt = "Visit a park.",
                            ResponseKind = "Photo",
                            Title = "Park"
                        },
                        new
                        {
                            Id = new Guid("84d1823d-145c-07a2-593f-f38e4d35e225"),
                            Category = "Adventure",
                            PackId = new Guid("4a1394b9-499d-15e5-78c6-afe1634365c4"),
                            Prompt = "Find street art.",
                            ResponseKind = "Photo",
                            Title = "Street art"
                        },
                        new
                        {
                            Id = new Guid("291d775d-4efe-9faa-8481-053ebdf38f05"),
                            Category = "Draw",
                            PackId = new Guid("2d45b383-1800-e3d8-1d40-cd0473582204"),
                            Prompt = "Draw each other from memory.",
                            ResponseKind = "Drawing",
                            Title = "Draw from memory"
                        },
                        new
                        {
                            Id = new Guid("7a089057-0f95-4a65-f0c7-a28a7a9e136c"),
                            Category = "Fun",
                            PackId = new Guid("2d45b383-1800-e3d8-1d40-cd0473582204"),
                            Prompt = "Finish: \"The best part of us is…\"",
                            ResponseKind = "Text",
                            Title = "Finish the sentence"
                        },
                        new
                        {
                            Id = new Guid("cf86d4bd-aaa0-8d97-4042-65cc5fb4a41f"),
                            Category = "Reflection",
                            PackId = new Guid("dac70586-bd06-9979-eab7-58ea6620321c"),
                            Prompt = "Best decision you made today?",
                            ResponseKind = "Text",
                            Title = "Best decision"
                        },
                        new
                        {
                            Id = new Guid("291c025f-6a80-e81d-a51c-b18f7ac5a54e"),
                            Category = "Reflection",
                            PackId = new Guid("dac70586-bd06-9979-eab7-58ea6620321c"),
                            Prompt = "Something you're grateful for.",
                            ResponseKind = "Text",
                            Title = "Grateful"
                        },
                        new
                        {
                            Id = new Guid("56cb0745-9534-6816-b5c5-cbffc6ba9b00"),
                            Category = "LoveLetter",
                            PackId = new Guid("deb2a561-3bc4-b63e-ffc9-ef5f1e1424cd"),
                            Prompt = "Share a favourite memory of us.",
                            ResponseKind = "Text",
                            Title = "Favourite memory"
                        },
                        new
                        {
                            Id = new Guid("194fc97a-0a52-a9e8-4a71-cf7748dc3f0d"),
                            Category = "LoveLetter",
                            PackId = new Guid("deb2a561-3bc4-b63e-ffc9-ef5f1e1424cd"),
                            Prompt = "Write a short letter to future us.",
                            ResponseKind = "Text",
                            Title = "Future letter"
                        },
                        new
                        {
                            Id = new Guid("7b41d0a2-4f28-f2f3-05de-e96d59c2b9da"),
                            Category = "LoveLetter",
                            PackId = new Guid("deb2a561-3bc4-b63e-ffc9-ef5f1e1424cd"),
                            Prompt = "Three compliments, right now.",
                            ResponseKind = "Text",
                            Title = "Three compliments"
                        },
                        new
                        {
                            Id = new Guid("0294f0f6-258e-b0fe-86c6-973a844710cd"),
                            Category = "Capture",
                            PackId = new Guid("e7a80ae9-5030-1bb0-0767-89342d30b30a"),
                            Prompt = "Photograph something growing.",
                            ResponseKind = "Photo",
                            Title = "Growing"
                        },
                        new
                        {
                            Id = new Guid("8d033758-505f-b30d-7657-8eb24f3c6f1e"),
                            Category = "Capture",
                            PackId = new Guid("e7a80ae9-5030-1bb0-0767-89342d30b30a"),
                            Prompt = "Photograph your favourite flower today.",
                            ResponseKind = "Photo",
                            Title = "Favourite flower"
                        },
                        new
                        {
                            Id = new Guid("63d5face-5ad3-b7d6-8b6b-24f6bf6bf177"),
                            Category = "Capture",
                            PackId = new Guid("e7a80ae9-5030-1bb0-0767-89342d30b30a"),
                            Prompt = "Find a bee.",
                            ResponseKind = "Photo",
                            Title = "Find a bee"
                        });
                });

            modelBuilder.Entity("Pulse.Api.ApiService.Domain.Pack", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Emoji")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("emoji");

                    b.Property<bool>("IsPro")
                        .HasColumnType("boolean")
                        .HasColumnName("is_pro");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("key");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_packs");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("ix_packs_key");

                    b.ToTable("packs", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a07a6b6e-62f5-dd5c-5c66-1a8d085aa450"),
                            Emoji = "✨",
                            IsPro = false,
                            Key = "core",
                            SortOrder = 0,
                            Title = "Core"
                        },
                        new
                        {
                            Id = new Guid("e172da09-9a11-fa64-c9af-ea552326293b"),
                            Emoji = "📸",
                            IsPro = true,
                            Key = "photography",
                            SortOrder = 1,
                            Title = "Photography"
                        },
                        new
                        {
                            Id = new Guid("4a1394b9-499d-15e5-78c6-afe1634365c4"),
                            Emoji = "🌍",
                            IsPro = true,
                            Key = "adventure",
                            SortOrder = 2,
                            Title = "Adventure"
                        },
                        new
                        {
                            Id = new Guid("2d45b383-1800-e3d8-1d40-cd0473582204"),
                            Emoji = "😂",
                            IsPro = true,
                            Key = "fun",
                            SortOrder = 3,
                            Title = "Fun"
                        },
                        new
                        {
                            Id = new Guid("dac70586-bd06-9979-eab7-58ea6620321c"),
                            Emoji = "🧠",
                            IsPro = true,
                            Key = "reflection",
                            SortOrder = 4,
                            Title = "Reflection"
                        },
                        new
                        {
                            Id = new Guid("deb2a561-3bc4-b63e-ffc9-ef5f1e1424cd"),
                            Emoji = "💌",
                            IsPro = true,
                            Key = "romance",
                            SortOrder = 5,
                            Title = "Romance"
                        },
                        new
                        {
                            Id = new Guid("e7a80ae9-5030-1bb0-0767-89342d30b30a"),
                            Emoji = "🌱",
                            IsPro = true,
                            Key = "garden",
                            SortOrder = 6,
                            Title = "Garden"
                        });
                });

            modelBuilder.Entity("Pulse.Api.ApiService.Domain.Pulse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ConnectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("connection_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("boolean")
                        .HasColumnName("is_favorite");

                    b.Property<string>("Note")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("note");

                    b.Property<string>("Reaction")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("reaction");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uuid")
                        .HasColumnName("sender_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_pulses");

                    b.HasIndex("SenderId")
                        .HasDatabaseName("ix_pulses_sender_id");

                    b.HasIndex("ConnectionId", "CreatedAt")
                        .HasDatabaseName("ix_pulses_connection_id_created_at");

                    b.ToTable("pulses", (string)null);
                });

            modelBuilder.Entity("Pulse.Api.ApiService.Domain.PulseMood", b =>
                {
                    b.Property<Guid>("PulseId")
                        .HasColumnType("uuid")
                        .HasColumnName("pulse_id");

                    b.Property<string>("Emoji")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("emoji");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("text");

                    b.HasKey("PulseId")
                        .HasName("pk_pulse_moods");

                    b.ToTable("pulse_moods", (string)null);
                });

            modelBuilder.Entity("Pulse.Api.ApiService.Domain.PulseNeed", b =>
                {
                    b.Property<Guid>("PulseId")
                        .HasColumnType("uuid")
                        .HasColumnName("pulse_id");

                    b.Property<string>("Emoji")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("emoji");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("text");

                    b.HasKey("PulseId")
                        .HasName("pk_pulse_needs");

                    b.ToTable("pulse_needs", (string)null);
                });

            modelBuilder.Entity("Pulse.Api.ApiService.Domain.PulseThought", b =>
                {
                    b.Property<Guid>("PulseId")
                        .HasColumnType("uuid")
                        .HasColumnName("pulse_id");

                    b.Property<string>("Emoji")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("emoji");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("text");

                    b.HasKey("PulseId")
                        .HasName("pk_pulse_thoughts");

                    b.ToTable("pulse_thoughts", (string)null);
                });

            modelBuilder.Entity("Pulse.Api.ApiService.Domain.PulseTouch", b =>
                {
                    b.Property<Guid>("PulseId")
                        .HasColumnType("uuid")
                        .HasColumnName("pulse_id");

                    b.Property<string>("StrokeData")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("stroke_data");

                    b.HasKey("PulseId")
                        .HasName("pk_pulse_touches");

                    b.ToTable("pulse_touches", (string)null);
                });

            modelBuilder.Entity("Pulse.Api.ApiService.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("avatar_url");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsPro")
                        .HasColumnType("boolean")
                        .HasColumnName("is_pro");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("timezone");

                    b.Property<string>("Username")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_users_username")
                        .HasFilter("username IS NOT NULL");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Pulse.Api.ApiService.Domain.UserDevice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AppVersion")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("app_version");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DeviceModel")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("device_model");

                    b.Property<string>("DeviceName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("device_name");

                    b.Property<string>("FcmToken")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("fcm_token");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<string>("OsVersion")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("os_version");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("platform");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_devices");

                    b.HasIndex("FcmToken")
                        .IsUnique()
                        .HasDatabaseName("ix_user_devices_fcm_token");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_devices_user_id");

                    b.ToTable("user_devices", (string)null);
                });

            modelBuilder.Entity("Pulse.Api.ApiService.Domain.UserFavorite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("category");

                    b.Property<string>("Emoji")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("emoji");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_favorites");

                    b.HasIndex("UserId", "Category", "SortOrder")
                        .HasDatabaseName("ix_user_favorites_user_id_category_sort_order");

                    b.ToTable("user_favorites", (string)null);
                });

            modelBuilder.Entity("Pulse.Api.ApiService.Domain.Connection", b =>
                {
                    b.HasOne("Pulse.Api.ApiService.Domain.User", "UserA")
                        .WithMany()
                        .HasForeignKey("UserAId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_connections_users_user_a_id");

                    b.HasOne("Pulse.Api.ApiService.Domain.User", "UserB")
                        .WithMany()
                        .HasForeignKey("UserBId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_connections_users_user_b_id");

                    b.Navigation("UserA");

                    b.Navigation("UserB");
                });

            modelBuilder.Entity("Pulse.Api.ApiService.Domain.ConnectionPack", b =>
                {
                    b.HasOne("Pulse.Api.ApiService.Domain.Connection", "Connection")
                        .WithMany()
                        .HasForeignKey("ConnectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_connection_packs_connections_connection_id");

                    b.HasOne("Pulse.Api.ApiService.Domain.Pack", "Pack")
                        .WithMany()
                        .HasForeignKey("PackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_connection_packs_packs_pack_id");

                    b.Navigation("Connection");

                    b.Navigation("Pack");
                });

            modelBuilder.Entity("Pulse.Api.ApiService.Domain.Moment", b =>
                {
                    b.HasOne("Pulse.Api.ApiService.Domain.Connection", "Connection")
                        .WithMany()
                        .HasForeignKey("ConnectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_moments_connections_connection_id");

                    b.HasOne("Pulse.Api.ApiService.Domain.MomentTemplate", "Template")
                        .WithMany()
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_moments_moment_templates_template_id");

                    b.Navigation("Connection");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("Pulse.Api.ApiService.Domain.MomentResponse", b =>
                {
                    b.HasOne("Pulse.Api.ApiService.Domain.Moment", "Moment")
                        .WithMany("Responses")
                        .HasForeignKey("MomentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_moment_responses_moments_moment_id");

                    b.HasOne("Pulse.Api.ApiService.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_moment_responses_users_user_id");

                    b.Navigation("Moment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Pulse.Api.ApiService.Domain.MomentTemplate", b =>
                {
                    b.HasOne("Pulse.Api.ApiService.Domain.Pack", "Pack")
                        .WithMany("Templates")
                        .HasForeignKey("PackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_moment_templates_packs_pack_id");

                    b.Navigation("Pack");
                });

            modelBuilder.Entity("Pulse.Api.ApiService.Domain.Pulse", b =>
                {
                    b.HasOne("Pulse.Api.ApiService.Domain.Connection", "Connection")
                        .WithMany("Pulses")
                        .HasForeignKey("ConnectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pulses_connections_connection_id");

                    b.HasOne("Pulse.Api.ApiService.Domain.User", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pulses_users_sender_id");

                    b.Navigation("Connection");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("Pulse.Api.ApiService.Domain.PulseMood", b =>
                {
                    b.HasOne("Pulse.Api.ApiService.Domain.Pulse", "Pulse")
                        .WithOne("Mood")
                        .HasForeignKey("Pulse.Api.ApiService.Domain.PulseMood", "PulseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pulse_moods_pulses_pulse_id");

                    b.Navigation("Pulse");
                });

            modelBuilder.Entity("Pulse.Api.ApiService.Domain.PulseNeed", b =>
                {
                    b.HasOne("Pulse.Api.ApiService.Domain.Pulse", "Pulse")
                        .WithOne("Need")
                        .HasForeignKey("Pulse.Api.ApiService.Domain.PulseNeed", "PulseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pulse_needs_pulses_pulse_id");

                    b.Navigation("Pulse");
                });

            modelBuilder.Entity("Pulse.Api.ApiService.Domain.PulseThought", b =>
                {
                    b.HasOne("Pulse.Api.ApiService.Domain.Pulse", "Pulse")
                        .WithOne("Thought")
                        .HasForeignKey("Pulse.Api.ApiService.Domain.PulseThought", "PulseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pulse_thoughts_pulses_pulse_id");

                    b.Navigation("Pulse");
                });

            modelBuilder.Entity("Pulse.Api.ApiService.Domain.PulseTouch", b =>
                {
                    b.HasOne("Pulse.Api.ApiService.Domain.Pulse", "Pulse")
                        .WithOne("Touch")
                        .HasForeignKey("Pulse.Api.ApiService.Domain.PulseTouch", "PulseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pulse_touches_pulses_pulse_id");

                    b.Navigation("Pulse");
                });

            modelBuilder.Entity("Pulse.Api.ApiService.Domain.UserDevice", b =>
                {
                    b.HasOne("Pulse.Api.ApiService.Domain.User", "User")
                        .WithMany("Devices")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_devices_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Pulse.Api.ApiService.Domain.UserFavorite", b =>
                {
                    b.HasOne("Pulse.Api.ApiService.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_favorites_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Pulse.Api.ApiService.Domain.Connection", b =>
                {
                    b.Navigation("Pulses");
                });

            modelBuilder.Entity("Pulse.Api.ApiService.Domain.Moment", b =>
                {
                    b.Navigation("Responses");
                });

            modelBuilder.Entity("Pulse.Api.ApiService.Domain.Pack", b =>
                {
                    b.Navigation("Templates");
                });

            modelBuilder.Entity("Pulse.Api.ApiService.Domain.Pulse", b =>
                {
                    b.Navigation("Mood");

                    b.Navigation("Need");

                    b.Navigation("Thought");

                    b.Navigation("Touch");
                });

            modelBuilder.Entity("Pulse.Api.ApiService.Domain.User", b =>
                {
                    b.Navigation("Devices");
                });
#pragma warning restore 612, 618
        }
    }
}
