// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pulse.Api.ApiService.Data;

#nullable disable

namespace Pulse.Api.ApiService.Data.Migrations
{
    [DbContext(typeof(PulseDbContext))]
    [Migration("20260622053614_FavouritesAndPhrasePulses")]
    partial class FavouritesAndPhrasePulses
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Pulse.Api.ApiService.Domain.Connection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ConnectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("connected_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("InviteCode")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("invite_code");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<Guid>("UserAId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_a_id");

                    b.Property<Guid?>("UserBId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_b_id");

                    b.HasKey("Id")
                        .HasName("pk_connections");

                    b.HasIndex("InviteCode")
                        .IsUnique()
                        .HasDatabaseName("ix_connections_invite_code")
                        .HasFilter("invite_code IS NOT NULL");

                    b.HasIndex("UserAId")
                        .HasDatabaseName("ix_connections_user_a_id");

                    b.HasIndex("UserBId")
                        .HasDatabaseName("ix_connections_user_b_id");

                    b.ToTable("connections", (string)null);
                });

            modelBuilder.Entity("Pulse.Api.ApiService.Domain.Pulse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ConnectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("connection_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("boolean")
                        .HasColumnName("is_favorite");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uuid")
                        .HasColumnName("sender_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_pulses");

                    b.HasIndex("SenderId")
                        .HasDatabaseName("ix_pulses_sender_id");

                    b.HasIndex("ConnectionId", "CreatedAt")
                        .HasDatabaseName("ix_pulses_connection_id_created_at");

                    b.ToTable("pulses", (string)null);
                });

            modelBuilder.Entity("Pulse.Api.ApiService.Domain.PulseMood", b =>
                {
                    b.Property<Guid>("PulseId")
                        .HasColumnType("uuid")
                        .HasColumnName("pulse_id");

                    b.Property<string>("Emoji")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("emoji");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("text");

                    b.HasKey("PulseId")
                        .HasName("pk_pulse_moods");

                    b.ToTable("pulse_moods", (string)null);
                });

            modelBuilder.Entity("Pulse.Api.ApiService.Domain.PulseNeed", b =>
                {
                    b.Property<Guid>("PulseId")
                        .HasColumnType("uuid")
                        .HasColumnName("pulse_id");

                    b.Property<string>("Emoji")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("emoji");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("text");

                    b.HasKey("PulseId")
                        .HasName("pk_pulse_needs");

                    b.ToTable("pulse_needs", (string)null);
                });

            modelBuilder.Entity("Pulse.Api.ApiService.Domain.PulseThought", b =>
                {
                    b.Property<Guid>("PulseId")
                        .HasColumnType("uuid")
                        .HasColumnName("pulse_id");

                    b.Property<string>("Emoji")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("emoji");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("text");

                    b.HasKey("PulseId")
                        .HasName("pk_pulse_thoughts");

                    b.ToTable("pulse_thoughts", (string)null);
                });

            modelBuilder.Entity("Pulse.Api.ApiService.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("avatar_url");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("display_name");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("timezone");

                    b.Property<string>("Username")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_users_username")
                        .HasFilter("username IS NOT NULL");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Pulse.Api.ApiService.Domain.UserDevice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AppVersion")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("app_version");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DeviceModel")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("device_model");

                    b.Property<string>("DeviceName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("device_name");

                    b.Property<string>("FcmToken")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("fcm_token");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<string>("OsVersion")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("os_version");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("platform");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_devices");

                    b.HasIndex("FcmToken")
                        .IsUnique()
                        .HasDatabaseName("ix_user_devices_fcm_token");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_devices_user_id");

                    b.ToTable("user_devices", (string)null);
                });

            modelBuilder.Entity("Pulse.Api.ApiService.Domain.UserFavorite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("category");

                    b.Property<string>("Emoji")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("emoji");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_favorites");

                    b.HasIndex("UserId", "Category", "SortOrder")
                        .HasDatabaseName("ix_user_favorites_user_id_category_sort_order");

                    b.ToTable("user_favorites", (string)null);
                });

            modelBuilder.Entity("Pulse.Api.ApiService.Domain.Connection", b =>
                {
                    b.HasOne("Pulse.Api.ApiService.Domain.User", "UserA")
                        .WithMany()
                        .HasForeignKey("UserAId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_connections_users_user_a_id");

                    b.HasOne("Pulse.Api.ApiService.Domain.User", "UserB")
                        .WithMany()
                        .HasForeignKey("UserBId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_connections_users_user_b_id");

                    b.Navigation("UserA");

                    b.Navigation("UserB");
                });

            modelBuilder.Entity("Pulse.Api.ApiService.Domain.Pulse", b =>
                {
                    b.HasOne("Pulse.Api.ApiService.Domain.Connection", "Connection")
                        .WithMany("Pulses")
                        .HasForeignKey("ConnectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pulses_connections_connection_id");

                    b.HasOne("Pulse.Api.ApiService.Domain.User", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pulses_users_sender_id");

                    b.Navigation("Connection");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("Pulse.Api.ApiService.Domain.PulseMood", b =>
                {
                    b.HasOne("Pulse.Api.ApiService.Domain.Pulse", "Pulse")
                        .WithOne("Mood")
                        .HasForeignKey("Pulse.Api.ApiService.Domain.PulseMood", "PulseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pulse_moods_pulses_pulse_id");

                    b.Navigation("Pulse");
                });

            modelBuilder.Entity("Pulse.Api.ApiService.Domain.PulseNeed", b =>
                {
                    b.HasOne("Pulse.Api.ApiService.Domain.Pulse", "Pulse")
                        .WithOne("Need")
                        .HasForeignKey("Pulse.Api.ApiService.Domain.PulseNeed", "PulseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pulse_needs_pulses_pulse_id");

                    b.Navigation("Pulse");
                });

            modelBuilder.Entity("Pulse.Api.ApiService.Domain.PulseThought", b =>
                {
                    b.HasOne("Pulse.Api.ApiService.Domain.Pulse", "Pulse")
                        .WithOne("Thought")
                        .HasForeignKey("Pulse.Api.ApiService.Domain.PulseThought", "PulseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pulse_thoughts_pulses_pulse_id");

                    b.Navigation("Pulse");
                });

            modelBuilder.Entity("Pulse.Api.ApiService.Domain.UserDevice", b =>
                {
                    b.HasOne("Pulse.Api.ApiService.Domain.User", "User")
                        .WithMany("Devices")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_devices_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Pulse.Api.ApiService.Domain.UserFavorite", b =>
                {
                    b.HasOne("Pulse.Api.ApiService.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_favorites_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Pulse.Api.ApiService.Domain.Connection", b =>
                {
                    b.Navigation("Pulses");
                });

            modelBuilder.Entity("Pulse.Api.ApiService.Domain.Pulse", b =>
                {
                    b.Navigation("Mood");

                    b.Navigation("Need");

                    b.Navigation("Thought");
                });

            modelBuilder.Entity("Pulse.Api.ApiService.Domain.User", b =>
                {
                    b.Navigation("Devices");
                });
#pragma warning restore 612, 618
        }
    }
}
